{
 "title": "The Ultimate Redis Dashboard",
 "description": "A comprehensive Grafana dashboard for monitoring Redis instances using Prometheus. This dashboard visualizes key metrics related to performance, memory, clients, keys, and replication.",
 "tags": [
  "prometheus",
  "redis"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "namespace",
    "label": "namespace",
    "query": {
     "query": "label_values(redis_up,namespace)"
    }
   },
   {
    "name": "instance",
    "label": "instance",
    "query": {
     "query": "label_values(redis_up{namespace=\"$namespace\"},instance)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Configuration", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Redis Version",
   "type": "stat",
   "description": "Redis Version",
   "gridPos": { "h": 4, "w": 5, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(redis_instance_info{namespace=\"$namespace\"}) by (redis_version)",
     "legendFormat": "{{redis_version}}"
    }
   ]
  },
  {
   "title": "MaxMemory Enabled?",
   "type": "stat",
   "description": "Check if the max memory feature is enabled in the configuration",
   "gridPos": { "h": 4, "w": 4, "x": 5, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(redis_config_maxmemory{namespace=\"$namespace\",instance=~\"$instance\"})",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "description": "Per node uptime",
   "gridPos": { "h": 9, "w": 7, "x": 9, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(redis_uptime_in_seconds{namespace=\"$namespace\",instance=~\"$instance\"}) by (instance)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "IO Threads Per Instance",
   "type": "stat",
   "description": "Represents the configured number of IO threads per instance",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(redis_config_io_threads{namespace=\"$namespace\",instance=~\"$instance\"}) by (instance)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Nodes",
   "type": "stat",
   "description": "number of nodes running the corresponding mode",
   "gridPos": { "h": 5, "w": 5, "x": 0, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(redis_instance_info{namespace=\"$namespace\",instance=~\"$instance\"}) by (redis_mode)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Eviction Policy",
   "type": "stat",
   "description": "When the maximum memory is reached, the configured policy will be applied.",
   "gridPos": { "h": 5, "w": 4, "x": 5, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(redis_instance_info{namespace=\"$namespace\",instance=~\"$instance\"}) by (instance,maxmemory_policy)",
     "legendFormat": "{{maxmemory_policy}}"
    }
   ]
  },
  { "title": "Performance", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 } },
  {
   "title": "Hit ratio per instance",
   "type": "timeseries",
   "description": "Hit rate shows the percentage of key space lookups that hit a key.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "increase(redis_keyspace_hits_total{namespace=~\"$namespace\",instance=~\"$instance\"}[1m]) / (increase(redis_keyspace_misses_total{namespace=~\"$namespace\",instance=~\"$instance\"}[1m]) + increase(redis_keyspace_hits_total{namespace=~\"$namespace\",instance=~\"$instance\"}[1m])) ",
     "legendFormat": "{{instance}}"
    },
    { "expr": "1", "legendFormat": "Target hit ratio for cache" }
   ]
  },
  {
   "title": "Requests Per Second",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "increase(redis_keyspace_hits_total{namespace=~\"$namespace\",instance=~\"$instance\"}[1m]) + increase(redis_keyspace_misses_total{namespace=~\"$namespace\",instance=~\"$instance\"}[1m])",
     "legendFormat": "{{instance}}"
    },
    {
     "expr": "sum(increase(redis_keyspace_hits_total{namespace=~\"$namespace\",instance=~\"$instance\"}[1m])) + sum(increase(redis_keyspace_misses_total{namespace=~\"$namespace\",instance=~\"$instance\"}[1m]))",
     "legendFormat": "total"
    }
   ]
  },
  {
   "title": "Hits Per Second",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "increase(redis_keyspace_hits_total{namespace=~\"$namespace\",instance=~\"$instance\"}[1m])",
     "legendFormat": "{{instance}}"
    },
    {
     "expr": "sum(increase(redis_keyspace_hits_total{namespace=~\"$namespace\",instance=~\"$instance\"}[1m]))",
     "legendFormat": "total"
    }
   ]
  },
  {
   "title": "Cache Misses Per Second",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "increase(redis_keyspace_misses_total{namespace=~\"$namespace\",instance=~\"$instance\"}[1m])",
     "legendFormat": "{{instance}}"
    },
    {
     "expr": "sum(increase(redis_keyspace_misses_total{namespace=~\"$namespace\",instance=~\"$instance\"}[1m]))",
     "legendFormat": "total"
    }
   ]
  },
  {
   "title": "Read/Write Ratio",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "(sum(rate(redis_commands_total{namespace=~\"$namespace\",instance=~\"$instance\",cmd=~\"get|mget\"}[1m])) by (instance)\n/\nsum(rate(redis_commands_total{namespace=~\"$namespace\",instance=~\"$instance\",cmd=~\"set|mset|hset|incr|decr\"}[1m])) by (instance)) >0",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Error Replies From Redis Instances",
   "type": "timeseries",
   "description": "Error replies that Redis sent to clients because of wrong commands, or internal error.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "increase(redis_total_error_replies{namespace=~\"$namespace\",instance=~\"$instance\"}[1m])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 35 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Total Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(redis_memory_used_bytes{namespace=~\"$namespace\",instance=~\"$instance\"})",
     "legendFormat": "Used Memory"
    },
    {
     "expr": "sum(redis_memory_max_bytes{namespace=~\"$namespace\",instance=~\"$instance\"})",
     "legendFormat": "Configured max memory"
    },
    {
     "expr": "sum(redis_memory_used_rss_bytes{namespace=~\"$namespace\",instance=~\"$instance\"})",
     "legendFormat": "Used RSS memory"
    },
    {
     "expr": "sum(redis_memory_used_bytes{namespace=~\"$namespace\",instance=~\"$instance\"}) by (instance) ",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Peak Memory Usage Per Instance",
   "type": "stat",
   "description": "Represents the maximum memory usage these instances have reached.",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(redis_memory_used_peak_bytes{namespace=\"$namespace\",instance=~\"$instance\"}) by (instance)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Clients Active Connections Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(increase(redis_mem_clients_normal{namespace=~\"$namespace\",instance=~\"$instance\"}[1m])) by (instance)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Slaves Active Connections Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(increase(redis_mem_clients_slaves{namespace=~\"$namespace\",instance=~\"$instance\"}[1m])) by (instance)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Jemalloc Fragmentation Ratio",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(redis_allocator_rss_ratio{namespace=~\"$namespace\",instance=~\"$instance\"}) by (instance)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Memory Waste Due to Fragmentation",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "(redis_allocator_rss_ratio{namespace=~\"$namespace\",instance=~\"$instance\"} * redis_memory_used_bytes{namespace=~\"$namespace\",instance=~\"$instance\"}) - redis_memory_used_bytes{namespace=~\"$namespace\",instance=~\"$instance\"}",
     "legendFormat": "{{instance}}"
    },
    {
     "expr": "sum((redis_allocator_rss_ratio{namespace=~\"$namespace\",instance=~\"$instance\"} * redis_memory_used_bytes{namespace=~\"$namespace\",instance=~\"$instance\"}) - redis_memory_used_bytes{namespace=~\"$namespace\",instance=~\"$instance\"})",
     "legendFormat": "total"
    }
   ]
  },
  { "title": "Keys", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 59 } },
  {
   "title": "Keys per DB",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 60 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum (redis_db_keys{namespace=~\"$namespace\",instance=~\"$instance\"}) by (db,instance) >0",
     "legendFormat": "{{db}} - {{instance}}"
    },
    {
     "expr": "sum (redis_db_keys{namespace=~\"$namespace\",instance=~\"$instance\"})",
     "legendFormat": "total"
    }
   ]
  },
  {
   "title": "Keys With No TTL",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 69 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum (redis_db_keys{namespace=~\"$namespace\",instance=~\"$instance\"}) by (instance) - sum (redis_db_keys_expiring{namespace=~\"$namespace\",instance=~\"$instance\"}) by (instance)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum (redis_db_keys{namespace=~\"$namespace\",instance=~\"$instance\"}) - sum (redis_db_keys_expiring{namespace=~\"$namespace\",instance=~\"$instance\"})",
     "legendFormat": "total"
    }
   ]
  },
  {
   "title": "Keys With TTL",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 69 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "redis_db_keys_expiring{namespace=~\"$namespace\",instance=~\"$instance\"} >0",
     "legendFormat": "{{instance}}"
    },
    {
     "expr": "sum (redis_db_keys_expiring{namespace=~\"$namespace\",instance=~\"$instance\"})",
     "legendFormat": "total"
    }
   ]
  },
  {
   "title": "Average TTL for the Expired Keys",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 76 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "increase(redis_db_avg_ttl_seconds{namespace=~\"$namespace\",instance=~\"$instance\"}[1m]) >0",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Expired Keys Per Second",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 76 },
   "targets": [
    {
     "expr": "increase(redis_expired_keys_total{namespace=~\"$namespace\",instance=~\"$instance\"}[1m])",
     "legendFormat": "{{instance}}"
    },
    {
     "expr": "sum(increase(redis_expired_keys_total{namespace=~\"$namespace\",instance=~\"$instance\"}[1m]))",
     "legendFormat": "total"
    }
   ]
  },
  {
   "title": "Expired Keys Percentage",
   "type": "timeseries",
   "description": "The percentage of keys that are probably expired. ",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 86 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "increase(redis_expired_stale_percentage{namespace=~\"$namespace\",instance=~\"$instance\"}[1m])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Key Evictions",
   "type": "timeseries",
   "description": "When the Maxmemory is reached, Redis will start the eviction according to the configured eviction policy.",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 86 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "increase(redis_evicted_keys_total{namespace=~\"$namespace\",instance=~\"$instance\"}[1m])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  { "title": "Clients", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 96 } },
  {
   "title": "Clients Connections Per Instance",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 97 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "redis_connected_clients{namespace=~\"$namespace\",instance=~\"$instance\"}",
     "legendFormat": "{{instance}}"
    },
    {
     "expr": "avg(redis_config_maxclients{namespace=~\"$namespace\"})",
     "legendFormat": "MaxPerInstance"
    }
   ]
  },
  {
   "title": "Blocked Clients Per Instance",
   "type": "timeseries",
   "description": "When the maximum number of allowed clients is reached, New clients will be blocked",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 97 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "redis_blocked_clients{namespace=~\"$namespace\",instance=~\"$instance\"}",
     "legendFormat": "{{instance}}"
    },
    {
     "expr": "sum(redis_blocked_clients{namespace=~\"$namespace\",instance=~\"$instance\"})",
     "legendFormat": "total"
    }
   ]
  },
  {
   "title": "Clients Max Reached Output Buffer",
   "type": "timeseries",
   "description": "Redis allocates an output buffer for every client connection. When a client is slow to read responses, the buffer starts filling up with pending data, which can grow until the client either catches up or exceeds the configured buffer limit.",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 104 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "redis_client_recent_max_output_buffer_bytes{namespace=~\"$namespace\",instance=~\"$instance\"} >0",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Clients Max Reached Input Buffer",
   "type": "timeseries",
   "description": "Redis allocates an input buffer for every client connection. When a client sends large commands or pipelines many commands at once, the buffer accumulates incoming data until Redis processes it, which can grow significantly depending on the workload.",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 104 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "redis_client_recent_max_input_buffer_bytes{namespace=~\"$namespace\",instance=~\"$instance\"} >0",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Timeout Clients",
   "type": "timeseries",
   "description": "When the client remains idle for a period greater than the configured time, then he will be added to the timeout table.",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 111 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "redis_clients_in_timeout_table{namespace=~\"$namespace\",instance=~\"$instance\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  { "title": "Cluster", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 118 } },
  {
   "title": "Cluster Shards",
   "type": "stat",
   "description": "Number Of Shards in the Cluster",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 119 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(redis_cluster_size{namespace=\"$namespace\"})",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Masters",
   "type": "stat",
   "description": "Number of masters in the cluster",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 119 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "redis_instance_info{namespace=\"$namespace\",role=\"master\",redis_mode=\"cluster\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Slaves",
   "type": "stat",
   "description": "Number of slaves in the cluster",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 119 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "redis_instance_info{namespace=\"$namespace\",role=\"slave\",redis_mode=\"cluster\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Cluster Bus Outgoing Communication Messages",
   "type": "timeseries",
   "description": "Number of communication messages sent by the corresponding cluster node.",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 126 },
   "targets": [
    {
     "expr": "increase(redis_cluster_messages_sent_total{namespace=\"$namespace\",instance=~\"$instance\"}[1m])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Cluster Bus Incoming Communication Messages",
   "type": "timeseries",
   "description": "Number of communication messages sent by the corresponding cluster node.",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 126 },
   "targets": [
    {
     "expr": "increase(redis_cluster_messages_received_total{namespace=\"$namespace\",instance=~\"$instance\"}[1m])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Connected slaves by instance",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 133 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(redis_connected_slaves{namespace=~\"$namespace\",instance=~\"$instance\"}) by (instance)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Cluster Assigned Slots",
   "type": "timeseries",
   "description": "Number of slots assigned to cluster nodes.",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 133 },
   "targets": [
    {
     "expr": "redis_cluster_slots_assigned{namespace=\"$namespace\",instance=~\"$instance\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Cluster Slots Failure",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 140 },
   "targets": [
    {
     "expr": "redis_cluster_slots_fail{namespace=\"$namespace\",instance=~\"$instance\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Cluster Slots Possible Failure",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 140 },
   "targets": [
    {
     "expr": "redis_cluster_slots_pfail{namespace=\"$namespace\",instance=~\"$instance\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Replication",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 147 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Connected Slaves",
   "type": "timeseries",
   "description": "number of slaves per master",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 148 },
   "targets": [
    {
     "expr": "redis_connected_slaves{namespace=\"$namespace\",instance=~\"$instance\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Connected Slaves Lag in Seconds",
   "type": "timeseries",
   "description": "number of slaves per master",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 148 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "redis_connected_slave_lag_seconds{namespace=\"$namespace\",instance=~\"$instance\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Accepted Partial Resync",
   "type": "timeseries",
   "description": "number of accepted partial rsync using the backlog buffer",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 155 },
   "targets": [
    {
     "expr": "increase(redis_replica_partial_resync_accepted{namespace=\"$namespace\",instance=~\"$instance\"}[1m])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Denied Partial Resync",
   "type": "timeseries",
   "description": "number of accepted partial rsync using the backlog buffer",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 155 },
   "targets": [
    {
     "expr": "increase(redis_replica_partial_resync_denied{namespace=\"$namespace\",instance=~\"$instance\"}[1m])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Accepted Full Replication",
   "type": "timeseries",
   "description": "number of accepted full rsync using the backlog buffer",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 162 },
   "targets": [
    {
     "expr": "increase(redis_replica_resyncs_full{namespace=\"$namespace\",instance=~\"$instance\"}[1m])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  { "title": "Commands", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 169 } },
  {
   "title": "Average Command Latency",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 170 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "expr": "(\n  sum by(cmd)(increase(redis_commands_latencies_usec_sum{namespace=~\"$namespace\",instance=~\"$instance\"}[1m]))\n  / on(cmd)\n  sum by(cmd)(increase(redis_commands_latencies_usec_count{namespace=~\"$namespace\",instance=~\"$instance\"}[1m]))\n)\n<(1/0)\n",
     "legendFormat": "{{cmd}} - {{le}}"
    }
   ]
  },
  {
   "title": "P99 Quantile",
   "type": "timeseries",
   "description": "What is the latency value that the 99% of requests are faster than?",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 170 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99,\n  sum by(le, cmd) (rate(redis_commands_latencies_usec_bucket[1m]))\n)\n"
    }
   ]
  },
  {
   "title": "Failed Commands",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 177 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "increase(redis_commands_failed_calls_total{namespace=~\"$namespace\",instance=~\"$instance\"}[1m]) > 0",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Rejected Commands",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 177 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by (cmd)(increase(redis_commands_rejected_calls_total{namespace=\"$namespace\",instance=~\"$instance\"}[1m])) >0",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  { "title": "Snapshotting (RDB)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 184 } },
  {
   "title": "RDB start",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 185 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "increase(redis_rdb_saves_total{namespace=\"$namespace\",instance=~\"$instance\"}[1m])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Changes Since Last RDB",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 185 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "redis_rdb_changes_since_last_save{namespace=\"$namespace\",instance=~\"$instance\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Last RDB Snapshot Duration",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 192 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "redis_rdb_last_bgsave_duration_sec{namespace=\"$namespace\",instance=~\"$instance\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Last COW Size",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 192 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "redis_rdb_last_cow_size_bytes{namespace=\"$namespace\",instance=~\"$instance\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  { "title": "Append Only File (AOF)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 199 } },
  {
   "title": "AOF Size",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 200 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "redis_aof_current_size_bytes{namespace=\"$namespace\",instance=~\"$instance\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "AOF Buffer Length",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 200 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "redis_aof_buffer_length{namespace=\"$namespace\",instance=~\"$instance\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "AOF Last Write Status",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 207 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "redis_aof_last_bgrewrite_status{namespace=\"$namespace\",instance=~\"$instance\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "AOF Delayed Fsync Due to OS",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 207 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "increase(redis_aof_delayed_fsync{namespace=\"$namespace\",instance=~\"$instance\"}[1m])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "AOF Rewrite Duration",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 214 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "increase(redis_aof_current_rewrite_duration_sec{namespace=\"$namespace\",instance=~\"$instance\"}[1m])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "AOF Last COW Size",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 214 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "redis_aof_last_cow_size_bytes{namespace=\"$namespace\",instance=~\"$instance\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  { "title": "I/O Threading", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 221 } },
  {
   "title": "Acitve IO Threads Per Instance",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 222 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "redis_io_threads_active{namespace=\"$namespace\",instance=~\"$instance\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "IO threads reads processed",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 222 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "increase(redis_io_threaded_reads_processed{namespace=\"$namespace\",instance=~\"$instance\"}[1m])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "IO threads writes processed",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 229 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "increase(redis_io_threaded_writes_processed{namespace=\"$namespace\",instance=~\"$instance\"}[1m])",
     "legendFormat": "{{instance}}"
    }
   ]
  }
 ]
}